---
title: "EASTD143B Digital Tools and Methods in East Asian Humanities: Coding Approach"
format: 
    revealjs:
        theme: simple
        incremental: true
        multiplex: true
---

**Meeting Time:** 09:00 - 11:45, Wednesdays, Spring 2025

**Location:** CGIS South S050 (FAS)

**Instructor:** Kwok-leong Tang (kwokleongtang@fas.harvard.edu)

**Office Hours:** 10:00 - 12:00, Thursdays (407 CGIS South)


## Overview 
This course is designed for East Asian humanities students interested in adopting digital methods in their research. It introduces AI-assisted coding for East Asian humanities projects and essential techniques for utilizing generative artificial intelligence (GenAI). Students completing the course will integrate and apply these tools into their research, exploring the rapidly evolving technologies related to humanities studies.

---

This course is for you if: 

* You come from a humanities background with no or little digital literacy but want to learn how digital tools and methods can benefit your studies or research.
* You want to bring digital components into your existing humanities research workflow.
* You have ideas for a digital project but need to know how to start.

---

This course may not be helpful to you if: 

* You are an experienced programmer.
* You have zero background in East Asian humanities.
* You are looking for data science or machine learning 101.
  
---

**ATTENTION**: Language and research requirements may apply. Proficiency in at least one East Asian language and a relevant research topic are required. Please contact Kwok-leong for more details about these requirements.
 

## Learning Goals 
After completion of the course, you will be able to:

- Use Python or command-line tools to collect data from the internet and digitized materials.
- Manipulate and analyze data with Python and AI tools.
- Test and use emerging artificial intelligence tools.
- Design and build a simple digital scholarship project.
 

## Class Format 
The weekly meetings are mostly hands-on. The course used to have non-mandatory coding sessions. However, we **DO NOT** have coding sessions this semester.


## Grading

- Class participation (20%): Students are expected to attend and participate in every class, completing assigned in-class exercises and engaging in discussions.
- Homework assignments (30%): Homework assignments will incorporate methods, principles, and tools into your research projects.
- Final project: The final project will include a meeting with Kwok-leong to discuss the project by the end of the third week (5%), a proposal (5%), a presentation (10%), a work journal (10%), and a final product (20%).
 

## Class Policies 

### Office Hours 
Kwok-leong’s in-person office hours are 10:00 - 12:00 on Thursdays, and online office hours are by appointment. Please email Kwok-leong to schedule appointments.

---

### Absence from Class 
Class participation accounts for 20% of your grade, so attendance is essential. However, we all face difficulties in our lives. Every enrolled student will have two opportunities to be absent from the weekly meeting.

---

### Classroom Rules 
All class materials will be shared on Canvas or Kwok-leong’s website. 
**Please do NOT take any photos or videos in class without Kwok-leong’s permission!**

---

### Accessibility Statement 
The instructor is committed to ensuring everyone has equitable access to the learning environment. Kwok-leong will strive to make the course materials, meetings, and the instructor’s office hours accessible and usable for all students. All materials distributed in the course will be available in an accessible format. The instructor will make reasonable accommodations to course materials, meetings, and office hours for students with disabilities who have registered with the Harvard Disability Access Office (DAO) or have been identified as having a disability or special need.

---

### Auditing

As the course will provide resources (API credits and subscription fees) to both enrolled and auditing students, auditing students are expected to commit to the course as enrolled students do. If you need to miss any class for any reason, please inform Kwok-leong in advance. Additionally, if you anticipate being absent for multiple meetings due to travel plans, it is recommended that you DO NOT audit this class.

--- 

## Weekly Schedule 

- 2025-01-29: Introduction and GenAI in General
- 2025-02-05: The Landscape of AI-Assisted Coding
- 2025-02-12: Version Control, Git, GitHub
- 2025-02-19: Package Managers, Libraries, Frameworks, and API
- 2025-02-26: Collecting Data I
- 2025-03-05: Collecting Data II
- 2025-03-12: Spring Break, 2025 AAS in Columbus, OH
- 2025-03-19: Text Analysis: Statistical Approach

## Weekly Schedule 

- 2025-03-26: Vector Search and Retrieval Augment Generation I
- 2025-04-02: Retrieval Augment Generation II
- 2025-04-09: Building a Digital Scholarship Project I 
- 2025-04-16: Building a Digital Scholarship Project II 
- 2025-04-23: Building a Digital Scholarship Project III 
- 2025-04-30: Presentations 


## Assignments

### Build a Personal Website with Quarto (10%) 
In this assignment, you will build a personal portfolio with Quarto, an open-source scientific and technical publishing system, and deploy it to GitHub Pages.

## Assignments

### Building a Web-Crawler (10%) 
In this assignment, you will create a web-crawler that can scrape any URL provided by the user.

## Assignments

### Building a Chatbot with Your Data (10%) 
Using the data provided by Kwok-leong, you will create a chatbot capable of interacting with and responding to queries about the data.

## Research Project
The core of this course is your research project. Kwok-leong encourages you to work on your thesis or dissertation project using the tools and methods introduced in this course. However, the project must bring new insights to the existing scholarship.

---

1.	**Topic Selection** (5%): Meet with Kwok-leong in person to decide your project topic by the end of the third week (2025-02-14).
2.	**Progress Presentations** (10% total): Each student will give two progress presentations in class (5% each).
3.	**Final Presentation** (10%): Each student will give a final presentation in the last class meeting.
4.	**Final Data Collection** (25%): Submit your project by the end of the grading deadline.

---

## Recommended Readings and Online Tutorials

The class does not require a textbook. Please watch the [Programming Concepts for Python course](https://www.linkedin.com/learning/programming-concepts-for-python) by the third week meeting. You should be able to access this video course by using your HarvardKey. For documentation and tutorials for specific tools that we use in class, links are in the weekly meeting materials.